name: Chromatic Deployment
on: [push, pull_request]
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: npm install
      
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.chpt_9c94a19b04e5778 }}
        with:
          projectToken: ${{ secrets.chpt_9c94a19b04e5778 }}
          autoAcceptChanges: true
          exitOnceUploaded: true