name: Chromatic Deployment 
on: push 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 
      - run: npm install 
      - uses: chromaui/action@v1 
        with: 
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} 
          autoAcceptChanges: true 
